name: Backend Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24.18.0'

    - name: Sync files to Production Directory
      run: |
        rsync -av --delete \
        --exclude='.git' \
        --exclude='.env' \
        --exclude='node_modules' \
        ./ /home/leegeon/cheatft/cheatft-api/ 

    - name: Install Dependencies
      run: |
        cd /home/ubuntu/cheat-ft-backend
        npm install

    - name: Restart PM2 Server
      run: |
        cd /home/ubuntu/cheat-ft-backend
        pm2 restart cheat-ft-backend --update-env || pm2 start src/index.js --name "cheat-ft-backend"